### ISSUE TITLE
Genart last call review of draft-ietf-httpapi-linkset-06

### ISSUE THREAD

**Issue by dret** [ietf-wg-httpapi/linkset#63] opened 2022-01-18 00:51 UTC
Reviewer: Christer Holmberg (@cdh4u)
Review result: Ready with Issues

I am the assigned Gen-ART reviewer for this draft. The General Area
Review Team (Gen-ART) reviews all IETF documents being processed
by the IESG for the IETF Chair.  Please treat these comments just
like any other last call comments.

For more information, please see the FAQ at

<https://trac.ietf.org/trac/gen/wiki/GenArtfaq>.

Document: draft-ietf-httpapi-linkset-06
Reviewer: Christer Holmberg
Review Date: 2022-01-10
IETF LC End Date: 2022-01-19
IESG Telechat date: Not scheduled for a telechat

Summary: Technically I don't have any major issue.  However, I do have a minor
technical, one administrative, and some editorial, comments.

Major issues:

Q1: The draft is intended to be published as Informational RFC. That sounds a
little strange to me. Could you please explain what the reason is?

Minor issues:

Q2: The document defines the "application/linkset+json" format, and indicates
that it can also be used for JSON-LD. What is the reason for not defining a
separate format for JSON-LD? Separate formats ("application/json" and
"application/ld+json") have previously been defined.

Nits/editorial comments:

Q3: The document has long sentences like "One serializes links in the same
format as used in HTTP the Link header field". Couldn't one just say "based on
the syntax of the HTTP Link header field", or something like that?

Q4: The document talks about "document format". People familiar with HTTP are
probably familiar with that terminology, but I think it would be good to add a
reference on first occurrence.

Q5: In Section 1, you talk about serializing links as JSON objects. Should it
be JSON strings, or something? JSON object is not a serialization.

-- 
Archived at: https://mailarchive.ietf.org/arch/msg/httpapi/TrnGm776OLDTZLsa5m3ly8K_nL4

**Comment by hvdsomp** [comment] 2022-01-19 15:05
Thanks for the review, @cdh4u. Regarding:

Q1: The I-D went through the HTTPAPI WG tagged as intended to be published as an Informational RFC. It do not  remember suggestions to go down a different path. Maybe @richsalz @darrelmiller have an opinion on whether or not Informational is inappropriate?

Q2: The I-D defines the `application/linkset+json` media type and leverages an established technique (provision of `context` as per as per [Section 6.8 of the W3C JSON-LD Recommendation](https://www.w3.org/TR/2014/
   REC-json-ld-20140116/#interpreting-json-as-json-ld) to allow that JSON to be interpreted as JSON-LD. This approach allows communities of use to specify a context that best serves their needs and does not require imposing specific vocabularies.

Q3: Yes, the sentence you suggest would work, although the "based on the syntax" bit might be interpreted as "that syntax with a few twists". I feel that the existing sentence does not leave such room for interpretation. A matter of preferred style, I guess.

Q4: The term `document format` doesn't sound quite appropriate, indeed. I suggest replacing the sentence:

Therefore, this specification defines two document formats that serialize Web Links and their attributes.

by the following sentence that matches the terminology used in the Abstract:

Therefore, this specification defines two document formats for representing sets of Web Links and their attributes as stand-alone documents.

Q5:  I suggest replacing the sentence:

One serializes links in the same format as used in HTTP the Link header field, and the other as a JSON object.

by:

One serializes links in the same format as used in HTTP the Link header field, and the other serializes links in JSON.

**Comment by hvdsomp** [comment] 2022-01-20 09:39
I think all feedback was addressed. OK to close?

**Comment by hvdsomp** [comment] 2022-01-21 09:28
Pinging @cdh4u to check whether it is OK to close this issue.

**Comment by cdh4u** [comment] 2022-01-21 11:29
Hi,

Please take a look at my latest reply regarding Q4.

Regarding Q1, I do think that “Informational” is not correct, but I will leave that for IESG to decide, so as far as I am concerned the issues has been addressed.

Regarding Q2, Q3 and Q5 I am ok with the modifications.

Regards,

Christer

**Comment by hvdsomp** [comment] 2022-01-21 11:34
I am pretty sure that there's no mentions of "document format" anymore in the I-D. There is "document" indeed. Am I understanding correctly that you want a reference to a document that explains what a "document" is?  Or are you suggesting using another term such as "file" because "document" is inappropriate e.g. because not widely understood? I am kind of not following anymore. Cheers, Herbert

**Comment by hvdsomp** [comment] 2022-01-21 13:43
Closing the issue since Q4 is now also resolved (see [https://github.com/ietf-wg-httpapi/linkset/commit/d6ae357303a0c2c4d36ec80075dc9e3b2b687c3a)](https://github.com/ietf-wg-httpapi/linkset/commit/d6ae357303a0c2c4d36ec80075dc9e3b2b687c3a). Will ping WG Chairs re the Informational comment of Q1.

**Closed by hvdsomp** 2022-01-21 13:43 UTC
